language: node_js
node_js:
  - 7
  
install:
  - npm install

script:
  - echo $CLASPRC_JSON > ~/.clasprc.json
  - echo $CLASP_JSON > .clasp.json
  - cat ~/.clasprc.json | head -2
  - npm run deploy
  